# Generated by Django 5.1.6 on 2025-04-23 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fix_member_association_field'),
        ('users', '0004_associationaccount_president_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.associationaccount'),
        ),
    ]
