# Generated by Django 5.1.6 on 2025-04-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_association'),
        ('api', '0005_add_association_to_project'),
    ]

    operations = [
    ]
