# Generated by Django 5.1.6 on 2025-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250423_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='needs_profile_completion',
            field=models.BooleanField(default=False, help_text='Indicates if this member needs to complete their profile'),
        ),
    ]
