# Generated by Django 5.1.6 on 2025-05-01 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_member_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cin',
            field=models.CharField(blank=True, help_text="Carte d'Identité Nationale (8 chiffres)", max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cin', message='CIN doit contenir exactement 8 chiffres', regex='^\\d{8}$')], verbose_name='CIN'),
        ),
    ]
