# Generated by Django 5.1.6 on 2026-02-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_member_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='api.member', verbose_name='Responsable du projet'),
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_notes', models.TextField(blank=True, verbose_name='Notes de réunion')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Fichier PDF')),
                ('is_final_report', models.BooleanField(default=False, verbose_name='Rapport final')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.member', verbose_name='Généré par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Rapport de projet',
                'verbose_name_plural': 'Rapports de projet',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('review', 'En révision'), ('done', 'Terminé'), ('blocked', 'Bloqué')], default='todo', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Heures estimées')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures réelles')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='api.member', verbose_name='Assigné à')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la phase')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(help_text="Ordre d'exécution de la phase", verbose_name='Ordre')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('validated', 'Validée')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Est validée')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validée le')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.project', verbose_name='Projet')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_phases', to='api.member', verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Phase de projet',
                'verbose_name_plural': 'Phases de projet',
                'ordering': ['project', 'order'],
                'unique_together': {('project', 'order')},
            },
        ),
    ]
