# Generated by Django 5.1.6 on 2026-02-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_priority_project_responsible_projectreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date réelle de fin'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.IntegerField(default=0, verbose_name='Pourcentage de progression'),
        ),
    ]
