# Generated by Django 5.1.6 on 2025-04-29 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(blank=True, help_text='Role of users who should receive this notification (leave blank for all)', max_length=50, null=True)),
                ('title', models.CharField(help_text='Short title for the notification', max_length=255)),
                ('message', models.TextField(help_text='Notification message')),
                ('notification_type', models.CharField(choices=[('meeting_scheduled', 'Meeting Scheduled'), ('meeting_cancelled', 'Meeting Cancelled'), ('meeting_reminder', 'Meeting Reminder'), ('report_due', 'Report Due'), ('report_overdue', 'Report Overdue'), ('transaction_created', 'Transaction Created'), ('transaction_updated', 'Transaction Updated'), ('transaction_deleted', 'Transaction Deleted'), ('donation_received', 'Donation Received'), ('user_joined', 'User Joined'), ('user_left', 'User Left'), ('admin_action_required', 'Admin Action Required'), ('official_letter_required', 'Official Letter Required'), ('budget_threshold', 'Budget Threshold'), ('monthly_summary', 'Monthly Summary')], help_text='Type of notification', max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related object (e.g., meeting ID, transaction ID)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of the related object (e.g., meeting, transaction)', max_length=50, null=True)),
                ('url', models.CharField(blank=True, help_text='URL to redirect to when notification is clicked', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the notification', max_length=10)),
                ('requires_action', models.BooleanField(default=False, help_text='Whether the notification requires action from the user')),
                ('action_deadline', models.DateTimeField(blank=True, help_text='Deadline for required action', null=True)),
                ('action_completed', models.BooleanField(default=False, help_text='Whether the required action has been completed')),
                ('action_completed_at', models.DateTimeField(blank=True, help_text='When the required action was completed', null=True)),
                ('requires_official_letter', models.BooleanField(default=False, help_text='Whether this notification requires sending an official letter')),
                ('official_letter_recipient', models.CharField(blank=True, help_text='Recipient for required official letter', max_length=255, null=True)),
                ('official_letter_sent', models.BooleanField(default=False, help_text='Whether the official letter has been sent')),
                ('official_letter_sent_at', models.DateTimeField(blank=True, help_text='When the official letter was sent', null=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='Specific user to receive this notification (leave blank for all)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficialLetterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Recipient of the letter', max_length=255)),
                ('subject', models.CharField(help_text='Subject of the letter', max_length=255)),
                ('content', models.TextField(help_text='Content of the letter')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number for the letter', max_length=50, null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Postal tracking number', max_length=50, null=True)),
                ('letter_file', models.FileField(blank=True, help_text='Digital copy of the letter', null=True, upload_to='official_letters/')),
                ('date_prepared', models.DateTimeField(auto_now_add=True, help_text='When the letter was prepared')),
                ('date_sent', models.DateTimeField(blank=True, help_text='When the letter was sent', null=True)),
                ('proof_of_sending', models.FileField(blank=True, help_text='Proof of sending (receipt, etc.)', null=True, upload_to='official_letters/proof/')),
                ('notification', models.OneToOneField(help_text='Related notification', on_delete=django.db.models.deletion.CASCADE, related_name='letter_log', to='notifications.notification')),
                ('sender', models.ForeignKey(help_text='User who sent the letter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_letters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_prepared'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['read'], name='notificatio_read_df532f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_role'], name='notificatio_recipie_7b216a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'),
        ),
    ]
