# Generated by Django 5.1.6 on 2025-05-04 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meeting_scheduled', 'Meeting Scheduled'), ('meeting_cancelled', 'Meeting Cancelled'), ('meeting_reminder', 'Meeting Reminder'), ('report_due', 'Report Due'), ('report_overdue', 'Report Overdue'), ('transaction_created', 'Transaction Created'), ('transaction_updated', 'Transaction Updated'), ('transaction_deleted', 'Transaction Deleted'), ('donation_received', 'Donation Received'), ('user_joined', 'User Joined'), ('user_left', 'User Left'), ('admin_action_required', 'Admin Action Required'), ('official_letter_required', 'Official Letter Required'), ('budget_threshold', 'Budget Threshold'), ('monthly_summary', 'Monthly Summary'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_completed', 'Project Completed'), ('project_milestone', 'Project Milestone Reached'), ('member_validated', 'Member Validated'), ('member_profile_updated', 'Member Profile Updated'), ('member_role_changed', 'Member Role Changed'), ('document_uploaded', 'Document Uploaded'), ('document_verified', 'Document Verified'), ('system_update', 'System Update'), ('account_security', 'Account Security Alert')], help_text='Type of notification', max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('web_notifications', models.BooleanField(default=True)),
                ('type_preferences', models.JSONField(default=dict)),
                ('email_priority_threshold', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('web_priority_threshold', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
