# Generated by Django 5.1.6 on 2025-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meeting_scheduled', 'Meeting Scheduled'), ('meeting_cancelled', 'Meeting Cancelled'), ('meeting_reminder', 'Meeting Reminder'), ('report_due', 'Report Due'), ('report_overdue', 'Report Overdue'), ('transaction_created', 'Transaction Created'), ('transaction_updated', 'Transaction Updated'), ('transaction_deleted', 'Transaction Deleted'), ('donation_received', 'Donation Received'), ('user_joined', 'User Joined'), ('user_left', 'User Left'), ('admin_action_required', 'Admin Action Required'), ('official_letter_required', 'Official Letter Required'), ('budget_threshold', 'Budget Threshold'), ('monthly_summary', 'Monthly Summary')], help_text='Type of notification', max_length=50),
        ),
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
