# Generated by Django 5.1.6 on 2025-04-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Association Law Assistant', max_length=100)),
                ('greeting_message', models.TextField(default="Bonjour! Je suis votre assistant spécialisé dans la législation tunisienne sur les associations. Comment puis-je vous aider aujourd'hui?")),
                ('farewell_message', models.TextField(default="Merci d'avoir utilisé mon service. N'hésitez pas à revenir si vous avez d'autres questions!")),
                ('model_path', models.CharField(default='mistral-7b-instruct-v0.1.Q4_K_M.gguf', max_length=255)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=256)),
                ('memory_window', models.IntegerField(default=5)),
                ('enable_conversation_enhancements', models.BooleanField(default=True)),
                ('enable_context_aware_responses', models.BooleanField(default=True)),
                ('enable_fallback_responses', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
            },
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='relevant_document_chunks',
            field=models.ManyToManyField(blank=True, related_name='messages', to='chatbot.documentchunk'),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10),
        ),
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.message')),
            ],
        ),
    ]
