# Generated by Django 5.1.6 on 2025-04-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_donor_association_donor_created_by'),
        ('users', '0004_associationaccount_president_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.associationaccount'),
        ),
    ]
