# Generated by Django 5.1.6 on 2025-04-24 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_transaction_association'),
        ('users', '0004_associationaccount_president_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='users.associationaccount'),
        ),
    ]
