# Generated by Django 5.1.6 on 2025-04-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_budgetallocation_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the donor is currently active'),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Indicates if the donor is internal to the organization but not a member'),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_member',
            field=models.BooleanField(default=False, help_text='Indicates if the donor is a member of the association'),
        ),
        migrations.AddField(
            model_name='donor',
            name='member_id',
            field=models.IntegerField(blank=True, help_text='Reference to the member if this donor is a member', null=True),
        ),
    ]
