# Generated by Django 5.1.6 on 2025-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_donor_is_active_donor_is_internal_donor_is_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_project_wide',
            field=models.BooleanField(default=False, help_text='Indicates if this expense applies to the entire project'),
        ),
    ]
