# Generated by Django 5.1.6 on 2025-05-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_transaction_is_project_wide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignDonationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_required', models.BooleanField(default=True)),
                ('letter_generated', models.BooleanField(default=False)),
                ('letter_file', models.FileField(blank=True, null=True, upload_to='finance/foreign_donation_letters/')),
                ('journal_publication_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_publication_date', models.DateField(blank=True, null=True)),
                ('reporting_deadline', models.DateField()),
                ('report_status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('acknowledged', 'Accusé de réception'), ('completed', 'Processus terminé')], default='pending', max_length=20)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_donation_report', to='finances.transaction')),
            ],
        ),
    ]
