# Generated by Django 5.1.6 on 2025-05-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_foreigndonationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigndonationreport',
            name='journal_publication_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
