# Generated by Django 5.1.6 on 2025-04-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_name_fields'),
    ]

    operations = [
    ]
