# Generated by Django 5.1.6 on 2025-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_only_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationaccount',
            name='president_email',
            field=models.EmailField(blank=True, help_text="Email of the association's president", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='associationaccount',
            name='secretary_email',
            field=models.EmailField(blank=True, help_text="Email of the association's general secretary", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='associationaccount',
            name='treasurer_email',
            field=models.EmailField(blank=True, help_text="Email of the association's treasurer", max_length=254, null=True),
        ),
    ]
