# Generated by Django 5.1.6 on 2025-04-26 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_associationaccount_president_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Indicates if the user has been validated by admin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
