# Generated by Django 5.1.6 on 2025-05-01 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_is_validated_customuser_validated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cin',
            field=models.CharField(help_text="Carte d'Identité Nationale (8 chiffres)", max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cin', message='CIN doit contenir exactement 8 chiffres', regex='^\\d{8}$')], verbose_name='CIN'),
        ),
    ]
